In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url="http://books.toscrape.com/catalogue/category/books/science_22/index.html" #This our web site link.
response=requests.get(url)

In [3]:
soup=BeautifulSoup(response.text,"html.parser")

In [4]:
def get_title(): #This function include all titles of books.
    title=[]
    for i in soup.find_all("h3"):
        title.append(i.get_text())
    return title
def get_price(): #This function include the price for each book.
    price=[]
    lst=[]
    for i in soup.find_all("p",attrs={'class':'price_color'}):
        lst.append(i.get_text())
    for i in lst:
        price.append(str(i)[1:]) #For select only usefl chars.
    return price
def get_rate(): #This function include all the rates for all books.
    lst1=[]
    lst2=[]
    lst3=[]
    rate=[]
    for i in soup.find_all("p"):
        lst1.append(str(i)[9:27]) #I selected this range for making sure i took all the desired chars.
    for i in range(0,42,3): #Now i'm appending only the rate.
        lst2.append(lst1[i]) 
    for i in lst2: #For deleting > from some rates.
        if str(i).endswith('>'):
            lst3.append(str(i)[0:17])
        else:
            lst3.append(i)
    for i in lst3: #For deleting " from the rates. 
        rate.append(str(i)[1:len(i)-1])
    return rate

In [5]:
df=pd.DataFrame(data={'Title':get_title(),'Price':get_price(),'Rate':get_rate()}) #Print data as data frame.

In [6]:
df

                                      Title   Price              Rate
0               The Most Perfect Thing: ...  £42.96  star-rating Four
1        Immunity: How Elie Metchnikoff ...  £57.36  star-rating Five
2                 Sorting the Beef from ...  £44.74  star-rating Four
3              Tipping Point for Planet ...  £37.55   star-rating One
4                     The Fabric of the ...  £55.91   star-rating One
5                    Diary of a Citizen ...  £28.41   star-rating One
6                     The Origin of Species  £10.01  star-rating Four
7                          The Grand Design  £13.76  star-rating Thre
8                Peak: Secrets from the ...  £16.28   star-rating Two
9   The Elegant Universe: Superstrings, ...  £13.03  star-rating Four
10          The Disappearing Spoon: And ...  £57.35  star-rating Five
11            Surely You're Joking, Mr. ...  £25.83   star-rating Two
12               Seven Brief Lessons on ...  £30.60  star-rating Four
13                         The Selfish Gene  £29.45   star-rating One

In [7]:
df.to_csv('Books_file.csv') #Save data into csv file.